---
bibliography: [references.yaml, references.bib]
editor: 
  markdown: 
    wrap: sentence
---

# Materials and Methods

## Sampling Design

The FLEA (Flanders Ecosystem Accounting) maps are raster-based maps of Flanders that are produced with a three year interval.
Each raster cell measures 10 m by 10 m.
The goal for the sampling design is to provide both validation of ecosystem changes between map datums and unbiased estimates of the changes in area.

As a first step, we construct the sampling frame by combining the $p$ maps into maps of change following the procedure in @gong2023.
Maps were available for $p = 3$ years: 2016, 2019 and 2022.
For each ecosystem class, we considered the union of the three periods (any raster cell where the ecosystem was present in at least one of the $K$ periods) and encoded each raster cell into "stable" (`111`), "gained" (`001`, `011`), "lost" (`110`, `100`), and "other complex patterns" (`101`, `010`), yielding a maximum of 4 strata per ecosystem type.
Each of the $p$ maps has categorical raster values encoding for $K = 16$ ecosystem types.
Thus, we obtain $16 \times 4 = 64$ strata.

Within each stratum, we select a spatially balanced sample of raster cells for which we make use of the same `GRTS` master sample that is used for the carbon monitoring network (`Cmon`) [@sleutel2020] and which is redistributed as a raster map [@vancalster2024].
The coordinate reference system, resolution and origin of the raster map are the same as used for the ecosystem maps, which makes them compatible and easy in use for selection of probabilistic spatially balanced samples.
Each raster cell of the `GRTS` master sampling raster map holds a ranking number.
These numbers can be used to draw spatially balanced samples of size $n$ for strata within the bounding box by sorting the ranks from low to high and selecting the $n$ lowest ranks (after cropping the raster file with the boundaries of the stratum).

Because spatially balanced samples tend to be well-spread across the spatial domain (avoiding clustered selection of sampling locations), we expect that within a stratum, say "forest gained", the selected sampling units will naturally reflect the area shares of constituent ecosystem transitions.
For instance, if half of the area "forest gained" is a transition from grassland to forest, we expect half of the sampling units to be located within that specific transition.
It is however not guaranteed that every transition will be part of the sample due to finite sample sizes and relative small area shares of some transitions.

As a rule, we allocated 80 sampling units to the "stable" class for each ecosystem and 240 sampling units to the classes representing changes in ecosystem type (i.e. "gained", "lost", "other complex pattern").
Only change classes that represent at least 10 ha are considered.
The allocation of the 240 sampling units to the "gained", "lost" and "other complex pattern" substrata is done proportional to the map area of these substrata, with the constrained that each substratum receives at least 40 sampling units.

## Response Design

### Definition of Ecosystems

*To be completed*

### Choice of Sampling Unit

- **Primary Sampling Unit (PSU):** A square polygon (block) with dimensions of $\sqrt{n_2} \times \sqrt{n_2}$ pixels (for example, 9 $\times$ 9 pixels).
- **Secondary Sampling Unit (SSU):** A 10 m $\times$ 10 m pixel.

In practice, however, the procedure is as follows:

- Select a block of $\sqrt{n_2} \times \sqrt{n_2} = n_2$ pixels.
- The entire block is digitized (subdivided into polygons, with a primary and an alternative label assigned to each polygon).
- This polygon map of the block is rasterized, and this rasterization provides the reference value for each pixel within a block.

This approach gives us a lot of freedom in the analysis stage (see @analysis).

### Reference Data Used

Regarding the **resolution of the aerial photographs (orthophotos)**, the medium-scale photographs from 2023 have a resolution of 15 cm.
In the year 2000, this was still 1 m.
Therefore, it is possible that the resolution evolved during the period from 2013 to 2022.
As a result, photographs used to validate a 2013 ecosystem map might be less accurate than those available for 2022.

## Analysis

Due to the more complex sampling design (balancing precision and cost-efficiency), the standard formulas provided in @olofsson2014 will only apply at the PSU level.
However, this sampling design retains the flexibility to calculate accuracy and area estimates for different scenarios in post-processing.
For instance, if we define a PSU as a block of 9 $\times$ 9 pixels, we can:

- Determine the label at the PSU level for both the reference data and the map, and subsequently process them using the formulas from @olofsson2014.
  - The rules for determining this label must be explicitly defined (e.g., using a majority rule or a binary classification).
- Determine the label on a subset of the PSU, such as the central 3 $\times$ 3 block of pixels, and process it identically.
- Utilize all information (from all pixels) to perform validation at the pixel level; in this case, formulas from model-assisted survey sampling literature and/or estimators for cluster sampling will likely be required for the analysis.
  - Here, too, a rule may be needed for assigning labels in the reference data when a polygon intersects a pixel.
- **Ecosystem Map:**
  - Calculate the mode class within each block.
  - This provides a stratification per class.
    - Merge strata if necessary.
    - Within each stratum, select a spatially balanced sample of $n$ clusters (= block of pixels = primary sampling unit or PSU).
    - Within each block (PSU), evaluate each of the $M$ secondary sampling units (SSU) (= pixels).

@cochran1977 provides the formula to determine the effect of cluster size when using cluster sampling to estimate a proportion:

$$\begin{aligned}
\text{total sum of squares} &= \text{within sum of squares} + \text{between sum of squares} \\
NMP(1-P) &= M\sum_{i=1}^n{(p_i - P)^2} + Mp_i(1-p_i)
\end{aligned}$$

This relationship can be used to calculate the various variance components as a function of the cluster size $M$.
This allows us to evaluate whether an optimal cluster size exists purely in terms of variance (disregarding costs for now).
