---
title: "Evaluatie van tweede test validatieprotocol"
author: "Hans Van Calster"
date: "2026-09-08"
format:
  html:
    toc: true
    code-fold: true
    code-summary: "Code"
    embed-resources: true
---

```{r}
#| label: setup
#| include: FALSE
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(dplyr)
library(ggplot2)
library(sf)
library(here)
library(units)
library(tidyr)
library(googlesheets4)
gs4_auth("*inbo.be")

flea_data <- gsub("extent", "data", here())


conflicted::conflicts_prefer(dplyr::filter)
library(INBOtheme)
set_theme(theme_inbo(base_size = 9))
```

```{r}
#| label: load-targets
library(targets)
library(terra)
withr::with_dir(
  new = rprojroot::find_root(rprojroot::is_git_root),
  code = {
    Sys.setenv(TAR_PROJECT = "validation_sample")
    tar_load(validation_polygons_50)
    tar_load(catstable)
  }
)
```

## Inlezen data

```{r}
#| label: read-notes
notes_po <- readxl::read_excel(
  file.path(
    flea_data,
    "validation_test2",
    "data_po",
    "grts_validatie_test2_PO.xlsx"
  )
) |>
  janitor::clean_names() |>
  rename(
    grts_rank = rankingnummer,
    time_minutes = tijd_min
  ) |>
  mutate(
    grts_rank = as.numeric(grts_rank),
    validator = "PO",
    method = "polygons"
  ) |>
  filter(
    !is.na(grts_rank)
  )

notes_sds <- read_sheet(
  ss = "1KIlnm29zWeUtWQF-1ZkR2fK1o0pO92K4LAdbFgCLy_Y",
  range = "A4:C35"
) |>
  janitor::clean_names() |>
  filter(!is.na(min)) |>
  rename(
    grts_rank = grts,
    time_minutes = min,
    opmerking = opmerkingen_bij_polygoonvalidatie
  ) |>
  mutate(
    validator = "SDS",
    method = "polygons",
    grts_rank = purrr::map_dbl(grts_rank, \(x) x)
  )
```



```{r}
#| label: read-validation-data
validation_polys_po <- file.path(
  flea_data,
  "validation_test2",
  "data_po",
  "20260707_test_validation_sample_testset_30_validaties_PO.gpkg"
) |>
  read_sf(
    layer = "20260707_test_validation_sample__testset_30_validaties_PO"
  )
validation_polys_po <- validation_polys_po |>
  rename(
    prelabels = labels
  ) |>
  mutate(
    newlabels = paste(label_2016, label_2019, label_2022, sep = "-"),
    validator = "PO",
    method = "polygons"
  )

# validation polys Steven
validation_polys_sds <- file.path(
  flea_data,
  "validation_test2",
  "data_sds",
  "FLEA validatie 2.shp"
) |>
  read_sf()


validation_polys_sds <- validation_polys_sds |>
  rename(
    prelabels = labels
  ) |>
  mutate(
    newlabels = paste(label_2016, label_2019, label_2022, sep = "-"),
    validator = "SDS",
    method = "polygons"
  )


validation_polys_sds <- validation_polys_sds |>
  select(-fid_1)
names(validation_polys_sds) <- names(validation_polys_po)
validation_polys_sds <- st_set_geometry(validation_polys_sds, "geom")

validation_polys <- bind_rows(
  validation_polys_po,
  validation_polys_sds
)

design_meta <- validation_polys_po |>
  distinct(grts_rank, stratum_name, changecat, area_labeled) |>
  mutate(
    stratum = sprintf(
      "%s (%s)",
      stringr::str_extract(stratum_name, "\\d+"),
      changecat
    )
  )

notes <- bind_rows(notes_po, notes_sds) |>
  left_join(design_meta, by = join_by(grts_rank))


validation_polygons_50 <- vect(validation_polygons_50)
```

```{r}
#| label: check-validation-data
# prop polygonen met juist prelabel
validation_polys |>
  st_drop_geometry() |>
  summarise(
    sum(prelabels == newlabels) / n(),
    .by = c(validator)
  )

# check polygonen onvolledig gevalideerd
validation_polys |>
  st_drop_geometry() |>
  select(validator, grts_rank, newlabels, label_2016, label_2019, label_2022) |>
  filter(
    grepl("other", newlabels)
  )

# check oppervlakte
validation_polys %>%
  mutate(
    area_m2 = st_area(.)
  ) |>
  st_drop_geometry() |>
  group_by(validator, grts_rank) |>
  summarise(area_m2 = sum(area_m2)) |>
  filter(
    !between(as.numeric(area_m2), 2490, 2501)
  )


# check joins
notes |>
  anti_join(
    validation_polys,
    by = join_by(validator, method, grts_rank)
  )
```

## Inschatting werklast

```{r}
glimpse(notes)
summary(notes)
```

```{r}
#| label: timing-results-average
notes |>
  ggplot() +
  geom_point(
    aes(x = validator, y = time_minutes, group = grts_rank)
  ) +
  geom_line(
    aes(x = validator, y = time_minutes, group = grts_rank)
  ) +
  stat_summary(
    fun.data = mean_cl_boot,
    aes(x = validator, y = time_minutes),
    colour = INBOtheme::inbo_felrood
  )
```

```{r}
#| label: timing-results-by-strata
notes |>
  ggplot() +
  geom_point(
    aes(x = validator, y = time_minutes, group = grts_rank, colour = stratum),
    position = position_dodge(width = 0.2), alpha = 0.3
  ) +
  geom_line(
    aes(x = validator, y = time_minutes, group = grts_rank, colour = stratum),
    position = position_dodge(width = 0.2), alpha = 0.3
  ) +
  stat_summary(
    fun.data = mean_cl_boot,
    aes(x = validator, y = time_minutes, colour = stratum),
    position = position_dodge(width = 0.2)
  )
```

```{r}
#| label: timings-extrapolation
# inschatting tijd nodig voor volledige validatie
mean_times <- notes |>
  group_by(stratum_name) |>
  summarise(
    mean_time = mean(time_minutes)
  )

time_estimates <- values(validation_polygons_50) |>
  as_tibble() |>
  count(stratum_name, changecat) |>
  left_join(mean_times, by = join_by(stratum_name)) |>
  mutate(
    stratum_name = stringr::str_extract(stratum_name, "\\d+"),
    level = ifelse(stratum_name %in% c(101:106), 2, 1),
    mean_time = ifelse(
      is.na(mean_time) & level == 2,
      mean_times$mean_time[mean_times$stratum_name == "bc_104_changecat"],
      mean(mean_times$mean_time[mean_times$stratum_name != "bc_104_changecat"])
    ),
    days = mean_time * n / 60 / 7.36
  )

time_estimates |>
  dplyr::filter(
    !stratum_name %in% c("600", "1000")
  ) |>
  summarise(
    n_halfway = sum(n) / 2,
    n_all = sum(n),
    days_halfway = sum(days) / 2,
    days_all = sum(days),
    pm_halfway = days_halfway / (160 / 12),
    pm_all = days_all / (160 / 12)
  ) |>
  knitr::kable(digits = 1)
```

## Vergelijking tussen validators

### Polygoon-gebaseerde validatie

```{r}
#| label: compare-polys
compare_polys <- st_make_valid(validation_polys_sds) |>
  st_intersection(
    st_make_valid(validation_polys_po)
  ) %>%
  mutate(
    area = st_area(.),
    id = seq_len(n())
  ) |>
  select(
    id,
    grts_rank,
    area,
    label_2016_sds = label_2016,
    label_2019_sds = label_2019,
    label_2022_sds = label_2022,
    label_2016_po = label_2016.1,
    label_2019_po = label_2019.1,
    label_2022_po = label_2022.1
  ) |>
  pivot_longer(
    cols = starts_with("label_"),
    names_to = c("year", "validator"),
    names_prefix = "label_",
    names_sep = "_",
    values_to = "label"
  ) |>
  pivot_wider(
    id_cols = c(id, grts_rank, area, year, geom),
    names_from = validator,
    values_from = label
  ) |>
  mutate(
    beoordeling = ifelse(sds == po, "zelfde", "verschillend")
  ) |>
  left_join(design_meta, by = join_by(grts_rank))
```

```{r}
#| label: compare-polys-by-strata
#| out-width: "100%"
compare_polys |>
  ggplot() +
  geom_col(
    aes(x = year, y = area, fill = beoordeling)
  ) +
  facet_wrap(vars(stratum))
```

```{r}
#| label: compare-polys-by-cells
#| out-width: "100%"
compare_polys |>
  ggplot() +
  geom_col(
    aes(x = year, y = area, fill = beoordeling)
  ) +
  facet_wrap(~ sprintf("%s (%s)", stratum, grts_rank))
```

```{r}
#| label: compare-polys-by-ecosystems
#| out-width: "100%"
compare_polys |>
  ggplot() +
  geom_col(
    aes(x = year, y = area, fill = beoordeling)
  ) +
  facet_grid(vars(sds), vars(po)) +
  guides(
    x = guide_axis(check.overlap = TRUE),
    y = guide_axis(check.overlap = TRUE)
  )
```


## Zij-aan-zij vergelijking per 50 m x 50 m polygoon


```{r}
#| label: maps
#| out-width: "100%"
#| fig-height: 8
#| fig-width: 8

comparison <- bind_rows(
  compare_polys |>
    mutate(
      method = "polys",
      po = po,
      sds = sds
    )
) |>
  pivot_longer(
    cols = c(po, sds),
    names_to = "validator",
    values_to = "value"
  ) |>
  left_join(
    catstable |> mutate(value = as.character(value)),
    by = join_by(value)
  ) |>
  mutate(
    stratum = sprintf(
      "%s (%s)",
      stringr::str_extract(stratum_name, "\\d+"),
      changecat
    )
  ) |>
  left_join(
    notes |>
      select(grts_rank, validator, opmerking) |>
      summarise(
        .by = c(grts_rank),
        opmerkingen = paste0(validator, ": ", opmerking) |>
          stringr::str_wrap() |>
          paste(collapse = "\n")
      ),
    by = join_by(
      grts_rank
    )
  )

all.equal(
  sort(unique(notes$grts_rank)),
  sort(unique(compare_polys$grts_rank))
)

flea_colours <- catstable$color
names(flea_colours) <- catstable$label

plot_map <- function(x, y, z) {
  opm <- x$opmerkingen[1]
  x |>
    ggplot() +
    geom_sf(
      aes(fill = label), # nolint: object_usage_linter.
      colour = "white",
      alpha = 0.8
    ) +
    facet_grid(
      rows = vars(method, validator), # nolint: object_usage_linter.
      cols = vars(year) # nolint: object_usage_linter.
    ) +
    scale_fill_manual(values = flea_colours) +
    theme_void() +
    labs(
      title = sprintf("stratum = %s, grts_rank = %s", y, z),
      subtitle = opm
    )
}

comparison_nest <- comparison |>
  nest(.by = c(grts_rank, stratum)) |>
  mutate(
    map = purrr::pmap(
      .l = list(
        x = data,
        y = stratum,
        z = grts_rank
      ),
      .f = plot_map
    )
  )

comparison_nest$map
```


