---
bibliography: [references.yaml, references.bib]
---

# Materiaal en methoden

## Landgebruikskaart Vlaanderen

@poelmans2019landgebruik en @poelmans2021 beschrijven de gebruikte databronnen en de methodes die werden gebruikt om de landgebruikskaarten te produceren.
De verschillende databronnen worden samengevoegd in een landgebruiksbestand.
Dit bestand bestaat uit een combinatie van zowel GIS-lagen (vector- en rasterbestanden) en andere (ruimtelijke) databanken.
Dit landgebruiksbestand en de databronnen die erin zitten, worden om de drie jaar geactualiseerd.
Het eerste jaar waarvoor dit beschikbaar is, is 2013.
De toestand van een landgebruiksbestand in een bepaald jaar, zal niet noodzakelijk overal een juiste weerspiegeling zijn van de toestand in dat jaar.
Het is de laatst gekende -- en dus mogelijk gedateerde -- toestand volgens een bepaalde databron.

De landgebruikskaarten zijn afgeleide (raster) producten op basis van de informatie in de landgebruiksbestanden.
De gegevens zijn volgens een bepaalde volgorde samengevoegd in een geodatabase met 4 rasterlagen met een 10m-resolutie (1 are):

-   niveau 1 bodembedekking (22 klassen)

-   niveau 2 verstedelijkt landgebruik (39 klassen)

-   niveau 3 multifunctioneel landgebruik (6 klassen)

-   niveau 4 haventerreinen en militaire domeinen (2 klassen)

Deze lagen worden in een bepaalde volgorde verder gecombineerd tot een eenlagige gebiedsdekkende landgebruikskaart.

In @poelmans2019landgebruik en @poelmans2021 werd een methodiek gebruikt die resulteerde in een landgebruikskaart met 18 klassen.
Deze methode legt een aantal zaken vast die bepalen hoe de (een) landgebruikskaart eruit zal zien:

-   de verschillende landgebruiksklassen, evenals een hiërarchisch systeem om landgebruiken te clusteren op hogere niveaus

-   welke databronnen gebruikt worden voor welke landgebruiksklassen

-   welke aggregaties hiervoor nodig zijn (van klassen binnen één van de databronnen) en welke combinaties van databronnen hiervoor nodig zijn

-   de volgorde waarin landgebruiken worden toegewezen aan een rastercel

-   de ruimtelijke resolutie van het afgeleide rasterproduct

Er is dus flexibiliteit in welke methode juist gebruikt wordt en de keuzes die daarbij gemaakt worden hangen af van de doeleinden waarvoor de kaart gebruikt zal worden.
Er moet enkel op toegezien worden dat dezelfde methode wordt gebruikt wanneer landgebruikskaarten van verschillende jaren met elkaar vergeleken worden.

Voor het Natuurrapport 2020 zijn er twee landgebruikskaarten (één voor 2013 en één voor 2016) gemaakt [@schneiders2020], die een andere methodiek gebruiken dan de landgebruikskaart die @poelmans2019landgebruik en @poelmans2021 bespreken.
Voor de analyses in @schneiders2020 werd een classificatie in tien ecosystemen (landgebruiken) gebruikt en hiervoor werd de bodembedekkingslaag van het Landgebruiksbestand Vlaanderen als volgt aangepast:

-   In het Schelde-estuarium zijn de slikken en schorren aangepast op basis van ecotopenkaarten voor 2013 en 2016, waarbij de slikken en schorren voorrang krijgen op de waterlaag of andere terrestrische klassen (bv. overig laag groen).

-   In het IJzer- en het Schelde-estuarium is het water in de zone onder getijdeninvloed geherklasseerd tot een extra klasse overgangswater, het overig water wordt beschouwd als zoetwater.

-   De wateroppervlakte voor de kust is uitgebreid tot het volledige Belgische deel van de Noordzee en als marien geklasseerd.

-   De bodembedekkingsklasse ruigte en struweel is opgesplitst in ruigte en struweel op basis van de rasterlaag BWK_natuur.

-   Landbouwpercelen die in 2015 (of 2012) als grasland zijn aangegeven en waarvoor in een of meer van de vier voorgaande jaren een andere teelt is aangegeven, zijn geherklasseerd als akker.
    Grasland krijgt hierdoor de betekenis van blijvend (vijfjarig) cultuurgrasland.
    Stappen 1 tot 5 resulteren in een aangepaste bodembedekkingskaart met 25 klassen.

-   De aangepaste bodembedekkingskaart is vervolgens samengevoegd met de niveaus 2 tot 4 van het Landgebruiksbestand Vlaanderen volgens de procedure beschreven in @poelmans2019landgebruik.
    Hierdoor wordt van de meeste ecosystemen een beperkte oppervlakte geherklasseerd naar stedelijk en bebouwd gebied.
    Er is afgeweken van de procedure van @poelmans2019landgebruik voor de cellen die als bodembedekking overig (d.w.z. onbekend) hebben en die buiten de zone verstedelijkt landgebruik (landgebruiksbestand, niveau 2) liggen.
    Die percelen zijn voor deze analyse meegeteld bij in de klasse stedelijk en bebouwd gebied.
    Dit leidt tot een aangepaste landgebruikskaart met 34 landgebruiksklassen (zie Tabel \@ref(tab:nara2020-aanpassingen) kolom 2).

-   De aangepaste landgebruikskaart wordt herleid tot een ecosysteemkaart met 10 klassen (zie Tabel \@ref(tab:nara2020-aanpassingen) kolom 3).
    Die indeling is gebaseerd op een ecosysteemtypologie voorgesteld door de Europese Commissie [@maes2013mapping; @maes2018mapping] en de richtlijnen van de Copernicus Land Monitoring Service.

```{r nara2020-aanpassingen}
nara2020_aanpassingen <- git2rdata::read_vc(
  "nara2020_aanpassingen_landgebruik",
  here::here("../../data")
) %>%
  mutate(
    across(everything(),
           ~ factor(
             .x,
             levels = stringr::str_sort(.x, numeric = TRUE) %>% unique())
    )
  ) %>%
  arrange(aangepaste_bodembedekkingskaart)

nara2020_aanpassingen %>%
  kable(
    caption = "Aanpassingen doorgevoerd voor NARA 2020 aan landgebruikskaart")
```

Een later project, dat hierop verder bouwde [@jocque2022], had tot doel om in een pilootproject verschillende verbeteropties voor deze landgebruikskaart te bekijken en na te gaan of de verbeterde kaarten effectief bijdroegen aan een hogere accuraatheid.
Er werden vier verschillende verbeteropties uitgetest en hiervan werd de accuraatheid geëvalueerd en vergeleken ten opzichte van de basiskaart die hierboven beschreven is en gebruikt werd in @schneiders2020.
De accuraatheid van de basiskaart werd reeds onder de loep genomen door middel van een validatiedataset van 3815 punten in [deze studie](https://www.vlaanderen.be/inbo/backgroundindicatoren/landgebruiksverandering-validatie).
Dezelfde validatieset werd gebruikt om de nieuwe kaarten met de volgende verbeteringen te evalueren:

-   Basiskaart + bos: Voor deze kaart werd de basiskaart verbeterd door gebruik te maken van de Boswijzer (beschikbaar voor 2009, 2015, 2018).
    Praktisch zou dit willen zeggen dat er een stap wordt toegevoegd in de bos-laag via de Digitale Boswijzer waarbij bossen voorrang krijgen op andere terrestrische klassen (bv. overig laag groen).

-   Basiskaart + gras: Door verkleuring van de vegetatie in droge jaren wordt laag groen vaak als overig geïdentificeerd.
    Blijvend grasland in landbouwgebruik wordt geïdentificeerd op basis van vijf opeenvolgende landbouwaangiftes.
    De aangifte geeft echter geen uitsluitsel of het grasland al dan niet omgeploegd wordt.
    Beide landgebruikstypes zouden beter in kaart gebracht kunnen worden via de analyse van kortetermijn tijdreeksen van satellietbeelden, zoals dat gebeurt voor de controle van het scheuren van poldergraslanden.

-   Basiskaart + bak: De bodemafdekkingskaart (BAK) heeft een resolutie van 5x5m en kan gebruikt worden om de verharde oppervlakte te identificeren binnen de klasse overig van de landgebruikskaart.
    Cellen overig die overlappen met de BAK blijven overig en de andere cellen worden laag groen.

-   Basiskaart + bos + gras + bak: Combinatie van de drie voorgaande kaarten.

Tevens wordt in @jocque2022 de link gelegd tussen deze landgebruikskaarten en de mogelijkheden die ze bieden om te rapporteren over ecosystem extent accounts volgens de richtlijnen die "The System of Environmental-Economic Accounting—Ecosystem Accounting (SEEA EA)" [@seea2021] meegeeft.
Het SEEA EA kader geeft de basis voor het opstellen van verschillende ecosysteemrekeningen met de volgende vijf belangrijkste ecosysteemrekeningen:

-   rekening voor de omvang van ecosystemen ("ecosystem extent account")

-   rekening voor de kwaliteit van ecosystemen ("ecosystem condition account")

-   rekening voor de ecosysteemdiensten in fysische eenheden ("ecosystem services flow account in physical terms")

-   rekening voor de ecosysteemdiensten in monetaire eenheden ("ecosystem services flow account in monetary terms")

-   monetaire rekening ecosysteemactiva ("monetary ecosystem asset account")

De rekening voor de omvang van ecosystemen vormt de basis voor alle daaropvolgende ecosysteemrekeningen en is daarom van groot belang.
Een rekening voor de omvang van ecosystemen meet de lokatie en oppervlakte van de verschillende ecosysteemtypes voor een bepaalde regio.
Een ecosysteemrekening slaat gewoonlijk op een bepaalde periode.
Voor deze periode geeft de rekening voor de omvang van ecosystemen de toestand weer aan het begin en het einde van deze periode, evenals de oppervlaktewijzigingen tussen ecosystemen over deze periode (wat is veranderd en wat is hetzelfde gebleven?).

Het EEA stelt een drieledige aanpak voor om rekeningen van de omvang van ecosystemen in Europa te ontwikkelen [@seea2021].
Niveau I omvat ecosysteemklassen die overeenkomen en overlappen met de brede ecosysteemtypen die zijn ontwikkeld in het MAES-proces (Mapping and assessment of ecosystems and their services) (14 klassen).
De rekeningen van niveau II zorgen voor een verdere onderverdeling van de ecosysteemtypen van niveau I en omvatten 23 ecosysteemcategorieën.
De rekeningen van niveau III voegen nog meer resolutie toe, onderverdelen de rekeningen van niveau II verder en omvatten 30 ecosysteemtypen.

De 14 klassen van niveau I zijn:

1.  Artificial surfaces (including urban and associated areas)

2.  Herbaceous crops

3.  Woody crops

4.  Multiple or layered crops

5.  Grassland

6.  Tree covered areas

7.  Mangroves

8.  Shrub covered areas

9.  Shrubs and/or herbaceous vegetation, aquatic or regularly flooded

10. Sparsely natural vegetated areas

11. Terrestrial barren land

12. Permanent snow and glaciers

13. Inland water bodies

14. Coastal water bodies and inter-tidal areas

## Schatting van de oppervlakte en accuraatheid van landgebruiken

### Algemeen protocol

@olofsson2014

@stehman2011 bespreken de invloed van de keuze van de steekproefeenheid op de uitkomsten van de accuraatheidsschattingen.
Ze vergelijken daarbij pixels, blokken van pixels en polygonen als mogelijke alternatieve steekproefeenheden.
Ze concluderen dat deze keuze een belangrijk effect heeft op OA, UA en PA.
Ze kunnen echter geen duidelijke verklaring geven voor deze verschillen.
@gu2020 stellen dat pixel-gebaseerde accuraatheidsschattingen geen goed idee zijn wanneer positionele accuraatheid een issue is.
Dit probleem wordt erger in heterogene landschappen en naarmate de landgebruiksclassificatie meer klassen telt.
@gu2021 gingen hetzelfde effect na voor blokken van pixels en stellen dat dit te verkiezen is. @radoux2017 gaan dieper in op de specifieke kwesties die komen kijken bij accuraatheidsschattingen op basis van polygonen.
Zij geven formules voor OA, UA en PA die aangepast zijn voor polygoon-gebaseerde accuraatheidsschattingen door rekening te houden met de oppervlakte van de polygonen.
Formules voor de variantie geven ze echter enkel voor OA.
We merken ook op dat blokken van pixels als steekproefeenheid niet mogen verward worden met pixels als steekproefeenheid in combinatie met cluster sampling.
In het eerste geval kennen we slechts één label toe aan de blok van pixels, terwijl in het laatste geval elke pixel in een cluster een label krijgt (waarbij die cluster ook de vorm kan aannemen van een blok).

@wickham2021 gebruiken voor het protocol om labels toe te kennen aan de referentieset zowel een primair als een alternatief referentielabel.
Ze berekenen UA en PA zowel op basis van overeenkomst met enkel het primaire label als overeenkomst met het primaire of het alternatieve label.

@radoux2020 werken het idee uit om een map-pixel te valideren op basis van een subsample uit referentiedata met veel hogere resolutie waarbij de grootte van de subsample niet op voorhand wordt vastgelegd, maar telkens meer en meer subsamples te evalueren tot dat het betrouwbaarheidsinterval uitsluitsel geeft over het toe te kennen label (bv in het geval van een binaire classificatie waarbij je zegt dat de kaartpixel bos is indien meer dan 50% van de pixeloppervlakte bos is, moet het betrouwbaarheidsinterval volledig boven 50% liggen).

@radoux2017 en @radoux2020 geven aan dat er verschillende types van labeling zijn waarop legendes van een kaart steunen:

-   agglomeratieve classificaties

    -   legendes waarbij labels volgens een meerderheidsregel worden toegekend: dus de meest voorkomende klasse binnen de ruimtelijke eenheid wordt het label van de ruimtelijke eenheid

    -   legendes waar een binaire classificatie gevolgd wordt (bos versus niet bos): in dit geval wordt de klasse die meer dan 50% voorkomt het label van de ruimtelijke eenheid (in tegenstelling tot voorgaande waar de meest voorkomende klasse ook minder dan 50% kan zijn in geval van meer dan twee klassen binnen de ruimtelijke eenheid)

    -   regelgebaseerde legendes

-   semantische classificaties:

    -   objectgeoriënteerde legendes, waartoe landgebruiksklassen vaak behoren

@radoux2020 geven de volgende mogelijke foutenbronnen voor referentiedata die bepaald worden op basis van interpretatie van luchtfoto's:

-   fouten tengevolge van verslappende aandacht

-   systematische fouten tengevolge van incorrecte interpretatie van de informatie op de luchtfoto

-   fouten tengevolge van variabiliteit op niveau van sub-samples binnen een steekproefeenheid

### Verschillende soorten van vertekening
