---
bibliography: [references.yaml, references.bib]
---

# Materiaal en methoden

## Typologie van landgebruik

TODO

## Steekproefontwerp

-   ecosysteemkaart
    -   bereken mode klasse in blok
    -   dit geeft stratificatie per klasse
        -   eventueel strata samenvoegen
        -   binnen elk stratum ruimtelijk gebalanceerde steekproef van $n$ clusters (= blok van pixels = primary sampling unit of PSU)
        -   binnen elk blok (PSU) wordt elk van $M$ secundary sampling units (SSU) bekeken (= pixels)

In @cochran1977 vinden we de formule om te bepalen wat het effect van de grootte van een cluster is bij cluster sampling voor het schatten van een proportie:

```{=tex}
\begin{align*}
\text{total sum of squares} &= \text{within sum of squares}  + \text{between sum of squares}\\
NMP(1-P) &= M\sum_{i=1}^n{(p_i - P)^2} + Mp_i(1-p_i)
\end{align*}
```
Deze relatie kan gebruikt worden om de verschillende variantiecomponenten in functie van de clustergrootte $M$ te berekenen.
Hiermee kan dan gekeken worden of er een optimale clustergrootte is in termen van enkel variantie (kosten zijn hier nog buiten beschouwing).

## Response design

### Definitie ecosystemen

### Keuze steekproefeenheid

-   Primaire steekproefeenheid (PSU): vierkante polygoon (blok) met afmeting $\sqrt{n_2}*\sqrt{n_2}$ pixels (bijvoorbeeld 9 x 9 pixels)
-   Secundaire steekproefeenheid (SSU): pixel 10 m x 10 m

maar in de praktijk gaan we als volgt te werk:

-   blok van $\sqrt{n_2}*\sqrt{n_2} = n_2$ pixels
-   volledige blok wordt gedigitaliseerd (opgedeeld in polygonen en aan elke polygoon wordt een primair label toegekend en een alternatief label)
-   deze polygoonkaart van het blok wordt verrasterd en deze verrastering levert ons de referentiewaarde voor elke pixel binnen een blok

### Gebruikte referentiedata

Wat de **resolutie van de orthofoto's** betreft, de middenschalige foto's van 2023 hebben een resolutie van 15 cm.
In het jaar 2000 was dat nog 1 m.
Het zou dus wel kunnen dat voor de periode 2013 tot 2022 er was evolutie zit op die resolutie, en dat foto's voor het valideren van een ecosysteemkaart van 2013, minder nauwkeurig zijn dan die voor 2022.

## Analyse

Omwille van het complexere steekproefontwerp (afweging precisie en kostenefficiëntie) zullen de standaard formules opgegeven in @olofsson2014 enkel gelden op niveau van de PSU's.
Met dit steekproefontwerp hebben we achteraf nog de flexibiliteit om accuraatheid en oppervlakteschattingen voor verschillende scenario's te berekenen.
Stel bijvoorbeeld dat we als PSU een blok nemen van 9 x 9 pixels:

-   bepalen van label op niveau van PSU voor referentiedata en kaart en vervolgens verwerken volgens formules in @olofsson2014
    -   hoe het label bepaald wordt, moeten we vastleggen in regels (bv volgens een meerderheidsregel of een binaire classificatie)
-   bepalen van label op deel van de PSU, bv de centrale 3 x 3 blok van pixels en vervolgens identiek verwerken
-   alle informatie gebruiken (van alle pixels) en dus validatie op pixelniveau; in dat geval wellicht formules uit de model-assisted survey sampling literatuur en/of schatters voor cluster sampling nodig om de analyse te doen.
    -   ook hier kan nog een regel nodig zijn voor toekenning van labels in de referentiedata in geval een polygoon een pixel doorsnijdt
